// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9uty2-taz6cmuXlSwk8NRdJ3yydDJ2Lc',
    appId: '1:815522571989:web:ab3d90792b03388b76a45c',
    messagingSenderId: '815522571989',
    projectId: 'task-manager-simmi-mad',
    authDomain: 'task-manager-simmi-mad.firebaseapp.com',
    storageBucket: 'task-manager-simmi-mad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_onOJP4TVu0bmZ_OoFUkyLNkqUs-uRRk',
    appId: '1:815522571989:android:4eb8897836963eeb76a45c',
    messagingSenderId: '815522571989',
    projectId: 'task-manager-simmi-mad',
    storageBucket: 'task-manager-simmi-mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6juBql7vUSg3b2_tOKwV4XOvXicR8LPw',
    appId: '1:815522571989:ios:fecae5b5b512532676a45c',
    messagingSenderId: '815522571989',
    projectId: 'task-manager-simmi-mad',
    storageBucket: 'task-manager-simmi-mad.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6juBql7vUSg3b2_tOKwV4XOvXicR8LPw',
    appId: '1:815522571989:ios:fecae5b5b512532676a45c',
    messagingSenderId: '815522571989',
    projectId: 'task-manager-simmi-mad',
    storageBucket: 'task-manager-simmi-mad.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9uty2-taz6cmuXlSwk8NRdJ3yydDJ2Lc',
    appId: '1:815522571989:web:4fe48b96d520271476a45c',
    messagingSenderId: '815522571989',
    projectId: 'task-manager-simmi-mad',
    authDomain: 'task-manager-simmi-mad.firebaseapp.com',
    storageBucket: 'task-manager-simmi-mad.firebasestorage.app',
  );
}
